bot:
  name: VladR_bot
  token: 1886697492:AAFINLXL4tpk0AWANojEIU2nLrAkI9DM2Uc

defaultMenuColumns: 3
defaultMenuRows: 4
spring:
  datasource:
    url: jdbc:postgresql://ec2-13-42-30-187.eu-west-2.compute.amazonaws.com:5432/postgres
    password: root
    username: postgres
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        order_updates: true
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles:
    active: dev
server:
  servlet:
    context-path: /bot

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://ec2-13-42-30-187.eu-west-2.compute.amazonaws.com:5432/dev

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://ec2-13-42-30-187.eu-west-2.compute.amazonaws.com:5432/prod
  jpa:
    hibernate:
      ddl-auto: validate
