bot:
  name: VladR_bot
  token: 1886697492:AAFINLXL4tpk0AWANojEIU2nLrAkI9DM2Uc
defaultMenuColumns: 3
defaultMenuRows: 4
spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        order_updates: true
    show-sql: true
logging:
  file:
    name: log.txt
    path: /logs
  level:
    com.pleasurebot.core: debug
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://35.176.106.181:5432/dev
    password: root
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://35.176.106.181:5432/prod
    password: root
    username: postgres
  jpa:
    hibernate:
      ddl-auto: validate
